config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
   sessions: "admin/sessions"
  }

  devise_for :customers, skip: :all
  devise_scope :customer do
    get '/customers/sign_up' => 'public/registrations#new', as: :new_customer_registration
    post '/customers' => 'public/registrations#create', as: :customer_registration
    get '/customers/sign_in' => 'public/sessions#new', as: :new_customer_session
    post '/customers/sign_in' => 'public/sessions#create', as: :customer_session
    delete '/customers/sign_out' => 'public/sessions#destroy', as: :destroy_customer_session
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, except: [:destroy, :new, :show]
    resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index]
    end
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'

  get 'items' => 'public/items#index'
  get 'items/:id' => 'public/items#show', as: :show_item
  get 'search' => 'public/items#search'

  get 'customers/my_page' => 'public/customers#show'
  get 'customers/edit' => 'public/customers#edit'
  patch 'customers/my_page' => 'public/customers#update'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw'

  get 'cart_items' => 'public/cart_items#index'
  patch 'cart_items/:id' => 'public/cart_items#update', as: :cart_item
  post 'cart_items' => 'public/cart_items#create'
  delete 'cart_items/destroy_all' => 'public/cart_items#destroy_all'
  delete 'cart_items/:id' => 'public/cart_items#destroy', as: 'destroy_cart_item'

  get 'orders/new' => 'public/orders#new'
  post 'orders/confirm' => 'public/orders#confirm'
  get 'orders/complete' => 'public/orders#complete'
  post 'orders' => 'public/orders#create'
  get 'orders' => 'public/orders#index'
  get 'orders/:id' => 'public/orders#show', as: :show_order

  get 'addresses' => 'public/addresses#index', as: 'public_addresses'
  post 'addresses' => 'public/addresses#create'
  get 'addresses/:id/edit' => 'public/addresses#edit', as: 'edit_public_address'
  patch 'addresses/:id' => 'public/addresses#update', as: 'public_address'
  delete 'addresses/:id' => 'public/addresses#destroy', as: 'destroy_public_address'

end

app/models/item.rb
class Item < ApplicationRecord

  attachment :image

  belongs_to :genre

  has_many :cart_items
  has_many :order_details

  enum is_active: { sale: true, stopsale: false }

  def self.search(keyword)
  where(["name like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def with_tax_price
    (price * 1.1).floor
  end


  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <h3>商品編集</h3>

      <%= form_with model:@item, url:admin_item_path(@item.id), local:true do |f| %>
      <table class="table table-borderless">
        <tr>
          <td><%= f.label :"商品画像" %></td>
          <td><%= f.attachment_field :image %></td>
        </tr>
        <tr>
          <td><%= f.label :"商品名" %></td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td><%= f.label :"商品説明" %></td>
          <td><%= f.text_area :introduction %></td>
        </tr>
        <tr>
          <td><%= f.label :"ジャンル" %></td>
          <td><%= f.select :genre_id, Genre.all.map { |genre| [genre.name, genre.id] } %></td>
        </tr>
        <tr>
          <td><%= f.label :"税抜価格" %></td>
          <td><%= f.text_field :price %>円</td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td><%= f.radio_button :is_active, :sale %><%= f.label :is_active, "販売中" %>
            <%= f.radio_button :is_active, :stopsale %><%= f.label :is_active, "販売停止中" %></td>
        </tr>
      </table>
      <button class="btn btn-success" type="submit">変更を保存</button>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <h3>商品一覧</h3>
      <div class="new-item">
        <%= link_to new_admin_item_path, class: 'text-dark' do%>
          <svg xmlns="http://www.w3.org/2000/svg" width="35" height="2¥35" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
          </svg>
        <% end %>
      </div>

      <table class="table table-borderless">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to admin_item_path(item.id) do %><%= item.name %><% end %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td><%= item.is_active_i18n %></td>
        </tr>
        <% end %>
      </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <h3>商品新規登録</h3>

      <%= form_with model:@item, url:admin_items_path, local:true do |f| %>
      <table class="table table-borderless">
        <tr>
          <td><%= f.label :"商品画像" %></td>
          <td><%= f.attachment_field :image %></td>
        </tr>
        <tr>
          <td><%= f.label :"商品名" %></td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td><%= f.label :"商品説明" %></td>
          <td><%= f.text_area :introduction %></td>
        </tr>
        <tr>
          <td><%= f.label :"ジャンル" %></td>
          <td><%= f.select :genre_id, Genre.all.map { |genre| [genre.name, genre.id] } %></td>
        </tr>
        <tr>
          <td><%= f.label :"税抜価格" %></td>
          <td><%= f.text_field :price %>円</td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td><%= f.radio_button :is_active, :sale %><%= f.label :is_active, "販売中" %>
            <%= f.radio_button :is_active, :stopsale %><%= f.label :is_active, "販売停止中" %></td>
        </tr>
        <tr>
          <td></td>
          <td><button class="btn btn-success" type="submit">新規登録</button></td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <div><h3>商品詳細</h3></div></br>
      <div class="item-show">

        <div class="item-image">
          <%= attachment_image_tag @item, :image, :fill, 100, 100, format: 'jpeg' %>
        </div>

        <div class="item-detail">

          <table>
            <tr>
              <td>商品名</td>
              <td><%= @item.name %></td>
            </tr>
            <tr>
              <td>商品説明</td>
              <td><%= @item.introduction %></td>
            </tr>
            <tr>
              <td>ジャンル</td>
              <td><%= @item.genre.name %></td>
            </tr>
            <tr>
              <td>税込価格（税抜価格）</td>
              <td><%= @item.with_tax_price %>（<%= @item.price %>）円</td>
            </tr>
            <tr>
              <td>ステータス</td>
              <td><%= @item.is_active_i18n %></td>
            </tr>
            <tr>
              <td><%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %></td>
            </tr>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>