config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
   sessions: "admin/sessions"
  }

  devise_for :customers, skip: :all
  devise_scope :customer do
    get '/customers/sign_up' => 'public/registrations#new', as: :new_customer_registration
    post '/customers' => 'public/registrations#create', as: :customer_registration
    get '/customers/sign_in' => 'public/sessions#new', as: :new_customer_session
    post '/customers/sign_in' => 'public/sessions#create', as: :customer_session
    delete '/customers/sign_out' => 'public/sessions#destroy', as: :destroy_customer_session
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, except: [:destroy, :new, :show]
    resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index]
    end
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'

  get 'items' => 'public/items#index'
  get 'items/:id' => 'public/items#show', as: :show_item
  get 'search' => 'public/items#search'

  get 'customers/my_page' => 'public/customers#show'
  get 'customers/edit' => 'public/customers#edit'
  patch 'customers/my_page' => 'public/customers#update'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw'

  get 'cart_items' => 'public/cart_items#index'
  patch 'cart_items/:id' => 'public/cart_items#update', as: :cart_item
  post 'cart_items' => 'public/cart_items#create'
  delete 'cart_items/destroy_all' => 'public/cart_items#destroy_all'
  delete 'cart_items/:id' => 'public/cart_items#destroy', as: 'destroy_cart_item'

  get 'orders/new' => 'public/orders#new'
  post 'orders/confirm' => 'public/orders#confirm'
  get 'orders/complete' => 'public/orders#complete'
  post 'orders' => 'public/orders#create'
  get 'orders' => 'public/orders#index'
  get 'orders/:id' => 'public/orders#show', as: :show_order

  get 'addresses' => 'public/addresses#index', as: 'public_addresses'
  post 'addresses' => 'public/addresses#create'
  get 'addresses/:id/edit' => 'public/addresses#edit', as: 'edit_public_address'
  patch 'addresses/:id' => 'public/addresses#update', as: 'public_address'
  delete 'addresses/:id' => 'public/addresses#destroy', as: 'destroy_public_address'

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy

  belongs_to :customer, dependent: :destroy

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_deposit: 0, deposited: 1, production: 2, preparing_ship: 3, shipped: 4 }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customer = Customer.find(params[:customer_id]).page(params[:page]).per(10)
    @orders = @customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @order.shipping_cost = 800
  end

  #注文ステータス・着手状況の更新
  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      if @order.status == "deposited"
        @order.order_details.update_all(making_status: "waiting_manufactured")
      end
      redirect_to admin_order_path(@order)
    else
      render :show
    end
  end


  private
  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <h3><%= @customer.last_name %> <%= @customer.first_name %>さんの注文履歴</h3>

      <table class="table table-borderless">
        <tr>
          <th>購入日時</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
        <% @orders.each do |order| %>
        <tr>
          <td><%= link_to admin_order_path(order.id) do %><%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %><% end %></td>
          <td>
            <% @sum = 0 %>
            <% order.order_details.each do |detail| %>
              <% @sum +=  detail.amount %>
            <% end %>
            <%= @sum %>
            </td>
            <td><%= order.status_i18n %></td>
          </tr>
        <% end %>
      </table>
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <h3>注文履歴詳細</h3>

      <table class="table table-borderless">
        <tr>
          <td>購入者</td>
          <td><%= @order.customer.last_name %><%= @order.customer.first_name %></td>
        </tr>
        <tr>
          <td>注文日</td>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <td>配送先</td>
          <td>〒<%= @order.postal_code %> <%= @order.address %> <%= @order.name %></td>
        </tr>
        <tr>
          <td>支払方法</td>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <td>注文ステータス</td>
          <td>
            <%= form_with model:@order, url:admin_order_path(@order), local:true do |f| %>
              <%= f.select :status, Order.statuses_i18n.keys.map { |status| [I18n.t("enums.order.status.#{status}"), status] } %>
              <button class="btn btn-success" type="submit">更新</button>
            <% end %>
          </td>
        </tr>
      </table>

      <div class="order_box">
        <div class="order_detail">
          <table class="table">
            <tr>
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th>製作ステータス</th>
            </tr>
            <% @order.order_details.each do |order_detail| %>
            <% @total = 0 %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.price %></td>
              <td><%= order_detail.amount %></td>
              <td><% @total += order_detail.price * order_detail.amount %><%= @total %></td>
              <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), local:true do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses_i18n.keys.map { |making_status| [I18n.t("enums.order_detail.making_status.#{making_status}"), making_status] } %>
                  <button class="btn btn-success" type="submit">更新</button>
                <% end %>
              </td>
            </tr>
            <% end %>
          </table>
        </div>

        <div class="order_account">
          <table class="account-table">
            <% @sum = @order.total_payment.to_i - @order.shipping_cost.to_i %>
            <tr>
              <td>商品合計</td>
              <td><%= @sum %></td>
            </tr>
            <tr>
              <td>送料</td>
              <td><%= @order.shipping_cost %></td>
            </tr>
            <tr>
              <td>請求金額合計</td>
              <td><%= @order.total_payment %></td>
            </tr>
          </table>
        </div>
      </div>

    </div>
  </div>
</div>