config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
   sessions: "admin/sessions"
  }

  devise_for :customers, skip: :all
  devise_scope :customer do
    get '/customers/sign_up' => 'public/registrations#new', as: :new_customer_registration
    post '/customers' => 'public/registrations#create', as: :customer_registration
    get '/customers/sign_in' => 'public/sessions#new', as: :new_customer_session
    post '/customers/sign_in' => 'public/sessions#create', as: :customer_session
    delete '/customers/sign_out' => 'public/sessions#destroy', as: :destroy_customer_session
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, except: [:destroy, :new, :show]
    resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index]
    end
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'

  get 'items' => 'public/items#index'
  get 'items/:id' => 'public/items#show', as: :show_item
  get 'search' => 'public/items#search'

  get 'customers/my_page' => 'public/customers#show'
  get 'customers/edit' => 'public/customers#edit'
  patch 'customers/my_page' => 'public/customers#update'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw'

  get 'cart_items' => 'public/cart_items#index'
  patch 'cart_items/:id' => 'public/cart_items#update', as: :cart_item
  post 'cart_items' => 'public/cart_items#create'
  delete 'cart_items/destroy_all' => 'public/cart_items#destroy_all'
  delete 'cart_items/:id' => 'public/cart_items#destroy', as: 'destroy_cart_item'

  get 'orders/new' => 'public/orders#new'
  post 'orders/confirm' => 'public/orders#confirm'
  get 'orders/complete' => 'public/orders#complete'
  post 'orders' => 'public/orders#create'
  get 'orders' => 'public/orders#index'
  get 'orders/:id' => 'public/orders#show', as: :show_order

  get 'addresses' => 'public/addresses#index', as: 'public_addresses'
  post 'addresses' => 'public/addresses#create'
  get 'addresses/:id/edit' => 'public/addresses#edit', as: 'edit_public_address'
  patch 'addresses/:id' => 'public/addresses#update', as: 'public_address'
  delete 'addresses/:id' => 'public/addresses#destroy', as: 'destroy_public_address'

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

end

app/models/item.rb
class Item < ApplicationRecord

  attachment :image

  belongs_to :genre

  has_many :cart_items
  has_many :order_details

  enum is_active: { sale: true, stopsale: false }

  def self.search(keyword)
  where(["name like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy

  belongs_to :customer, dependent: :destroy

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_deposit: 0, deposited: 1, production: 2, preparing_ship: 3, shipped: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: { cannot_manufactured: 0, waiting_manufactured: 1, making: 2, complete_manufactured: 3 }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def with_tax_price
    (price * 1.1).floor
  end


  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  

  def after_sign_up_path_for
    redirect_to root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active, :created_at, :updated_at])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_form.html.erb
<table class="table table-borderless">
  <tr>
    <th>ジャンル検索</th>
  </tr>

  <% @genres.each do |genre| %>
    <tr>
                           <!--（左：paramsで送るときの名前　右：入れる値）-->
      <td><%= link_to items_path(genre_id: genre.id) do %><%= genre.name %><% end %></td>
    </tr>
  <% end %>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="d-flex flex-column vh-100">
  <header class="shadow-sm">

    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <a class="navbar-brand p-3" href="/">ながのcake</a>

        <% if customer_signed_in? %>
          ようこそ、<%= current_customer.last_name %>さん！
          <% else %>
        <% end %>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <div class="d-grid gap-2 d-md-block">
            <% if customer_signed_in? %>
            <button type="button" class="btn btn-outline-dark btn-sm"><li class="nav-item">
              <%= link_to "マイページ", customers_my_page_path, class: 'nav-link text-dark'  %>
            </li></button>
            <button type="button" class="btn btn-outline-dark btn-sm"><li class="nav-item">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-dark'  %>
            </li></button>
            <button type="button" class="btn btn-outline-dark btn-sm"><li class="nav-item">
              <%= link_to "カート", cart_items_path(@customer), class: 'nav-link text-dark'  %>
            </li></button>
            <button type="button" class="btn btn-outline-dark btn-sm"><li class="nav-item">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark'  %>
            </li></button>
            <% else %>
            <% if admin_signed_in? %>
            <button type="button" class="btn btn-outline-dark btn-sm"><li class="nav-item">
              <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark'  %>
            </li></button>
            <button type="button" class="btn btn-outline-dark btn-sm"><li class="nav-item">
              <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark'  %>
            </li></button>
            <button type="button" class="btn btn-outline-dark btn-sm"><li class="nav-item">
              <%= link_to "注文履歴一覧", admin_path, class: 'nav-link text-dark'  %>
            </li></button>
            <button type="button" class="btn btn-outline-dark btn-sm"><li class="nav-item">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark'  %>
            </li></button>
            <button type="button" class="btn btn-outline-dark btn-sm"><li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark'  %>
            </li></button>
            <% else %>
            <button type="button" class="btn btn-outline-dark btn-sm"><li class="nav-item">
              <%= link_to "About", about_path, class: 'nav-link text-dark'  %>
            </li></button>
            <button type="button" class="btn btn-outline-dark btn-sm"><li class="nav-item">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-dark'  %>
            </li></button>
            <button type="button" class="btn btn-outline-dark btn-sm"><li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark'  %>
            </li></button>
            <button type="button" class="btn btn-outline-dark btn-sm"><li class="nav-item">
              <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark'  %>
            </li></button>
            <% end %>
            <% end %>
            </div>
          </ul>
        </div>
      </div>
    </nav>

    <div class="search-form">
        <%= form_with url: search_path, method: :get, local: true do |f| %>
          <%= f.text_field :keyword, value: @keyword %>
          <%= f.submit "検索" %>
        <% end %>
    </div>
  </header>

  <main class="mb-auto"><%= yield %></main>

  <footer class="bg-dark text-white pt-5 pb-5"></footer>

</body>